apiVersion: management.cattle.io/v3
kind: Cluster
metadata:
  annotations:
    authz.management.cattle.io/creator-role-bindings: '{"created":["cluster-owner"],"required":["cluster-owner"]}'
    field.cattle.io/creatorId: user-g8qfh
    lifecycle.cattle.io/create.cluster-agent-controller-cleanup: "true"
    lifecycle.cattle.io/create.cluster-scoped-gc: "true"
    lifecycle.cattle.io/create.mgmt-cluster-rbac-remove: "true"
  creationTimestamp: "2021-02-22T01:12:53Z"
  finalizers:
  - controller.cattle.io/cluster-agent-controller-cleanup
  - controller.cattle.io/cluster-scoped-gc
  - controller.cattle.io/cluster-provisioner-controller
  - controller.cattle.io/mgmt-cluster-rbac-remove
  generateName: c-
  generation: 14
  labels:
    cattle.io/creator: norman
    fleet.cattle.io/cluster-name: kvm
  managedFields:
  - apiVersion: management.cattle.io/v3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
      f:spec:
        .: {}
        f:displayName: {}
        f:dockerRootDir: {}
        f:enableClusterAlerting: {}
        f:enableClusterMonitoring: {}
        f:enableNetworkPolicy: {}
        f:internal: {}
        f:localClusterAuthEndpoint:
          .: {}
          f:enabled: {}
        f:rancherKubernetesEngineConfig:
          .: {}
          f:addonJobTimeout: {}
          f:authentication: {}
          f:dns:
            .: {}
            f:nodelocal: {}
          f:ignoreDockerVersion: {}
          f:ingress:
            .: {}
            f:provider: {}
          f:kubernetesVersion: {}
          f:monitoring:
            .: {}
            f:provider: {}
            f:replicas: {}
          f:network:
            .: {}
            f:options:
              .: {}
              f:flannel_backend_type: {}
            f:plugin: {}
          f:services:
            .: {}
            f:etcd:
              .: {}
              f:backupConfig:
                .: {}
                f:enabled: {}
                f:intervalHours: {}
                f:retention: {}
              f:creation: {}
              f:extraArgs:
                .: {}
                f:election-timeout: {}
                f:heartbeat-interval: {}
              f:retention: {}
              f:snapshot: {}
            f:kubeApi:
              .: {}
              f:secretsEncryptionConfig: {}
              f:serviceNodePortRange: {}
          f:sshAgentAuth: {}
          f:upgradeStrategy:
            .: {}
            f:maxUnavailableControlplane: {}
            f:maxUnavailableWorker: {}
            f:nodeDrainInput:
              .: {}
              f:gracePeriod: {}
              f:ignoreDaemonSets: {}
              f:timeout: {}
        f:scheduledClusterScan: {}
        f:windowsPreferedCluster: {}
      f:status:
        .: {}
        f:appliedEnableNetworkPolicy: {}
    manager: Go-http-client
    operation: Update
    time: "2021-02-22T01:12:53Z"
  - apiVersion: management.cattle.io/v3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:fleet.cattle.io/cluster-name: {}
      f:spec:
        f:agentImageOverride: {}
        f:answers: {}
        f:description: {}
        f:desiredAgentImage: {}
        f:desiredAuthImage: {}
        f:fleetWorkspaceName: {}
        f:rancherKubernetesEngineConfig:
          f:authorization: {}
          f:bastionHost: {}
          f:cloudProvider: {}
          f:dns:
            f:nodelocal:
              f:ipAddress: {}
          f:restore: {}
          f:services:
            f:etcd:
              f:backupConfig:
                f:s3BackupConfig: {}
            f:kubeController: {}
            f:kubelet: {}
            f:kubeproxy: {}
            f:scheduler: {}
          f:systemImages: {}
      f:status:
        f:agentImage: {}
        f:appliedPodSecurityPolicyTemplateId: {}
        f:appliedSpec:
          .: {}
          f:agentImageOverride: {}
          f:answers: {}
          f:description: {}
          f:desiredAgentImage: {}
          f:desiredAuthImage: {}
          f:displayName: {}
          f:enableClusterAlerting: {}
          f:enableClusterMonitoring: {}
          f:enableNetworkPolicy: {}
          f:internal: {}
          f:localClusterAuthEndpoint:
            .: {}
            f:enabled: {}
          f:windowsPreferedCluster: {}
        f:authImage: {}
        f:capabilities:
          .: {}
          f:loadBalancerCapabilities: {}
        f:eksStatus:
          .: {}
          f:securityGroups: {}
          f:subnets: {}
          f:upstreamSpec: {}
          f:virtualNetwork: {}
        f:provider: {}
    manager: rancher-operator
    operation: Update
    time: "2021-02-22T01:12:53Z"
  - apiVersion: management.cattle.io/v3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:authz.management.cattle.io/creator-role-bindings: {}
          f:lifecycle.cattle.io/create.cluster-agent-controller-cleanup: {}
          f:lifecycle.cattle.io/create.cluster-scoped-gc: {}
          f:lifecycle.cattle.io/create.mgmt-cluster-rbac-remove: {}
        f:finalizers: {}
      f:spec:
        f:rancherKubernetesEngineConfig:
          f:authentication:
            f:strategy: {}
          f:rotateEncryptionKey: {}
      f:status:
        f:allocatable:
          .: {}
          f:cpu: {}
          f:memory: {}
          f:pods: {}
        f:capabilities:
          f:ingressCapabilities: {}
          f:nodePortRange: {}
        f:capacity:
          .: {}
          f:cpu: {}
          f:memory: {}
          f:pods: {}
        f:conditions: {}
        f:driver: {}
        f:eksStatus:
          f:privateRequiresTunnel: {}
        f:limits:
          .: {}
          f:cpu: {}
          f:memory: {}
          f:pods: {}
        f:requested:
          .: {}
          f:cpu: {}
          f:memory: {}
          f:pods: {}
    manager: rancher
    operation: Update
    time: "2021-02-22T01:15:02Z"
  name: kvm
spec:
  agentImageOverride: ""
  answers: {}
  description: ""
  desiredAgentImage: ""
  desiredAuthImage: ""
  displayName: test
  dockerRootDir: /var/lib/docker
  enableClusterAlerting: false
  enableClusterMonitoring: false
  enableNetworkPolicy: false
  fleetWorkspaceName: fleet-default
  internal: false
  localClusterAuthEndpoint:
    enabled: true
  rancherKubernetesEngineConfig:
    addonJobTimeout: 45
    authentication:
      strategy: x509|webhook
    authorization: {}
    bastionHost: {}
    cloudProvider: {}
    dns:
      nodelocal:
        ipAddress: ""
    ignoreDockerVersion: true
    ingress:
      provider: nginx
    kubernetesVersion: v1.19.7-rancher1-1
    monitoring:
      provider: metrics-server
      replicas: 1
    network:
      options:
        flannel_backend_type: vxlan
      plugin: canal
    restore: {}
    rotateEncryptionKey: false
    services:
      etcd:
        backupConfig:
          enabled: true
          intervalHours: 12
          retention: 6
          s3BackupConfig: null
        creation: 12h
        extraArgs:
          election-timeout: "5000"
          heartbeat-interval: "500"
        retention: 72h
        snapshot: false
      kubeApi:
        secretsEncryptionConfig: {}
        serviceNodePortRange: 30000-32767
      kubeController: {}
      kubelet: {}
      kubeproxy: {}
      scheduler: {}
    sshAgentAuth: false
    systemImages: {}
    upgradeStrategy:
      maxUnavailableControlplane: "1"
      maxUnavailableWorker: 10%
      nodeDrainInput:
        gracePeriod: -1
        ignoreDaemonSets: true
        timeout: 120
  scheduledClusterScan: {}
  windowsPreferedCluster: false
status:
  agentImage: ""
  allocatable:
    cpu: "0"
    memory: "0"
    pods: "0"
  appliedEnableNetworkPolicy: false
  appliedPodSecurityPolicyTemplateId: ""
  appliedSpec:
    agentImageOverride: ""
    answers: {}
    description: ""
    desiredAgentImage: ""
    desiredAuthImage: ""
    displayName: ""
    enableClusterAlerting: false
    enableClusterMonitoring: false
    enableNetworkPolicy: null
    internal: false
    localClusterAuthEndpoint:
      enabled: false
    windowsPreferedCluster: false
  authImage: ""
  capabilities:
    ingressCapabilities:
    - customDefaultBackend: false
      ingressProvider: nginx
    loadBalancerCapabilities: {}
    nodePortRange: 30000-32767
  capacity:
    cpu: "0"
    memory: "0"
    pods: "0"
  conditions:
  - status: "True"
    type: Pending
  - lastUpdateTime: "2021-02-22T01:12:55Z"
    message: waiting for etcd and controlplane nodes to be registered
    reason: Provisioning
    status: Unknown
    type: Provisioned
  - lastUpdateTime: "2021-02-22T01:12:54Z"
    message: Waiting for API to be available
    status: Unknown
    type: Waiting
  - lastUpdateTime: "2021-02-22T01:12:54Z"
    status: "True"
    type: BackingNamespaceCreated
  - lastUpdateTime: "2021-02-22T01:12:54Z"
    status: "True"
    type: DefaultProjectCreated
  - lastUpdateTime: "2021-02-22T01:12:54Z"
    status: "True"
    type: SystemProjectCreated
  - lastUpdateTime: "2021-02-22T01:12:54Z"
    status: "True"
    type: InitialRolesPopulated
  - lastUpdateTime: "2021-02-22T01:12:54Z"
    status: "True"
    type: CreatorMadeOwner
  - lastUpdateTime: "2021-02-22T01:12:55Z"
    status: "True"
    type: NoDiskPressure
  - lastUpdateTime: "2021-02-22T01:12:55Z"
    status: "True"
    type: NoMemoryPressure
  driver: rancherKubernetesEngine
  eksStatus:
    privateRequiresTunnel: null
    securityGroups: null
    subnets: null
    upstreamSpec: null
    virtualNetwork: ""
  limits:
    cpu: "0"
    memory: "0"
    pods: "0"
  provider: ""
  requested:
    cpu: "0"
    memory: "0"
    pods: "0"
